{{- if (.Values.clusterController).enabled }}
#
# NOTE:
# The following ClusterRole permissions are only created and assigned for the
# cluster controller feature. They will not be added to any clusters by default.
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubecost.clusterControllerName" . }}
  labels:
    {{- include "cost-analyzer.commonLabels" . | nindent 4 }}
rules:
  - apiGroups: ['kubecost.com']
    resources: ['turndownschedules']
    verbs: ['list', 'watch', 'create', 'update', 'delete']
  - apiGroups: ['kubecost.com']
    resources: ['turndownschedules/status']
    verbs: ['update']
  - apiGroups: ['', 'events.k8s.io']
    resources: ['events']
    verbs: ['create', 'patch', 'update']
  - apiGroups: ['']
    resources: ['nodes']
    verbs: ['get', 'list'{{- if .Values.clusterController.clusterTurndown }}, 'patch'{{- end }}]
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['get', 'list'{{- if .Values.clusterController.clusterTurndown }}, 'delete'{{- end }}]
  - apiGroups: ['']
    resources: ['configmaps']
    verbs: ['get', 'update']
  - apiGroups: ['apps']
    resources: ['deployments', 'daemonsets']
    verbs: ['get', 'list', 'patch', 'update']
  - apiGroups: ['apps']
    resources: ['statefulsets', 'replicasets']
    verbs: ['get', 'update']
  - apiGroups: ['batch']
    resources: ['cronjobs', 'jobs']
    verbs: ['get', 'list', 'patch']
  - apiGroups: ['policy']
    resources: ['pods/eviction']
    verbs: ['create']
  # Used for namespace turndown 
  # When cleaning a namespace, we need the ability to remove
  # arbitrary resources (since we helm uninstall all releases in that NS first)
  {{- if .Values.clusterController.namespaceTurndown.rbac.enabled }}
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['list', 'get', 'delete']
  {{- end }}
{{- end }}